version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=craftbeer
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  craftbeer-api:
    image: guilhermedomingues/craft-beer-app
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:3306"]
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=app
      - DATABASE_PORT=3306
